pub const STATUS_NOTTRIED: u8 = 0;
pub const STATUS_IN_PROGRESS: u8 = 1;
pub const STATUS_SUCCESS_FINAL: u8 = 2;
pub const STATUS_NONFINAL_FAILURE: u8 = 3;
pub const STATUS_FINAL_FAILURE: u8 = 4;

pub const ERROR_OK: u8 = 0;
#[allow(dead_code)]
pub const ERROR_GENERIC_NONFINAL_FAILURE: u8 = 1;
pub const ERROR_GENERIC_FINAL_FAILURE: u8 = 2;
pub const ERROR_LN_ADDRESS_NONFINAL_FAILURE: u8 = 101;
pub const ERROR_LN_ADDRESS_FINAL_FAILURE: u8 = 102;
pub const ERROR_LN_BOLT11_INVOICE_NONFINAL_FAILURE: u8 = 111;
pub const ERROR_LN_BOLT11_INVOICE_FINAL_FAILURE: u8 = 112;
#[allow(dead_code)]
pub const ERROR_LN_BOLT11_INVOICE_NOT_ENOUGH_FUNDS: u8 = 113;
pub const ERROR_NOSTR_LN_ADDRESS_NONFINAL_FAILURE: u8 = 151;
#[allow(dead_code)]
pub const ERROR_NOSTR_LN_ADDRESS_FINAL_FAILURE: u8 = 152;
pub const ERROR_NOSTR_ZAP_NONFINAL_FAILURE: u8 = 161;
#[allow(dead_code)]
pub const ERROR_NOSTR_ZAP_FINAL_FAILURE: u8 = 162;
